#!/bin/python

import sys
import csv
import os

# this script appends hit data (0 or 1) to the datafile generated by get_dockdata.py
# the datafile is generated via the get_dockdata.py script

data_file = sys.argv[1] # generated via get_dockdata.py script

out_file = str(data_file[:-12]) + 'hitdata.txt'

with open(data_file, 'r') as dock_data:
    lines = dock_data.readlines()

hits = int(len(lines)*0.01)

out_lines = []

for i in range(len(lines)):
    line = str(lines[i])
    if i == 0:
        new = line[:-1]+',hit\n'
    else:
        if i <= hits:
            new = line[:-2]+',0\n'
        else:
            new = line[:-2]+',1\n'
    out_lines.append(new)

with open(out_file, 'w') as out:
    for i in range(len(out_lines)):
        out.write(out_lines[i])
